# Generated by Django 4.2.2 on 2023-06-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=1)),
                ('hunger', models.IntegerField(default=40)),
                ('happiness', models.IntegerField(default=40)),
            ],
        ),
    ]
